name: Setup Java Test
description: Test composite action for Java version updates

runs:
  using: composite
  steps:
    - uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 8
