name: Setup Java Test
description: Test composite action for Java version updates

runs:
  using: composite
  steps:
    - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
      with:
        distribution: temurin
        java-version: 8
