name: Setup Python Test
description: Test composite action for Python version updates

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: 3.14.2
