name: Setup Node.js Test
description: Test composite action for Node.js version updates

runs:
  using: composite
  steps:
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: 16.14.0
