name: 'Validate renovate config'

on:
  push:
    paths:
      - 'renovate.json5'

permissions:
  contents: read

jobs:
  validate_renovate:
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: ./.github/actions/setup-node

      - name: Validate renovate config
        run: npx -p renovate@41.116.7 renovate-config-validator